import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  careSideBar: [
    {
      type: 'doc',
      id: 'care/index',
      label: 'Care',
    },
    {
      type: 'category',
      label: 'User Documentation',
      items: [
        'care/user-documentation/questionnaire',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'care/development',
        },
      ],
    },
    {
      type: 'category',
      label: 'Care Apps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'care/apps',
        },
      ],
    },
    {
      type: 'category',
      label: 'ABDM',
      items: [
        {
          type: 'autogenerated',
          dirName: 'care/ABDM',
        },
      ],
    },
    {
      type: 'category',
      label: 'CEP',
      items: [
        {
          type: 'autogenerated',
          dirName: 'care/CEP',
        },
      ],
    },
    {
      type: 'category',
      label: 'HMIS',
      items: [
        {
          type: 'autogenerated',
          dirName: 'care/HMIS',
        },
      ],
    },
    {
      type: 'link',
      label: 'Contributor\'s Guide',
      href: '/docs/contributing',
    },
  ],
  leaderboardSideBar : [
    {
      type: 'category',
      label: 'Leaderboard',
      items: [{ type: 'autogenerated', dirName: 'leaderboard' }],
    }
  ],
  ayushmaSideBar: [
    {
      type: 'category',
      label: 'Ayushma',
      items: [{ type: 'autogenerated', dirName: 'ayushma' }],
    }
  ],
  devopsSideBar: [
    {
      type: 'category',
      label: 'DevOps',
      items: [{ type: 'autogenerated', dirName: 'devops' }],
    },
  ],
  contributorsSideBar: [
    {
      type: 'category',
      label: 'Contributing',
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },
  ],
};

export default sidebars;
